name: CSS Check
on: push
jobs:
  check-css-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check CSS
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      css: true
      with:
        root: ./
